### ISSUE TITLE
GCE: Improve check for ConnectWithPublicIPs()

### ISSUE THREAD

**Issue by justnoise** [elotl/kip#100]
Our check for `ConnectWithPublicIPs()` is `metadata.OnGCE()`.  That isn't sufficient.  We also need to make sure the controller is inside the same GCE private network as the client is configured to use.

To fix this, we can use `gceClient.detectCurrentVPC()` and ensure that matches the configured VPC.

**Comment by ldx** [comment]
Fixed via #109
