### ISSUE TITLE
Enable usage of custom VM size on GCP

### ISSUE THREAD

**Issue by myechuri** [elotl/kip#132]
Certain cloud providers, like GCP, offer creation of custom VM sizes (ex: 1vcpu, 13GB) instead of picking from boilerplate VM sizes (ex: `c2-standard-4`, `n1-standard-8`). If a kip user's application resource form factor is not a close fit for a boilerplate VM size, using boilerplate VM size leads to wasted resources (and compute spend). It would be useful to such kip users to consume custom VM size feature on a cloud provider, when available, so that their applications automatically consume the most resource and cost efficient compute.

Specifically, there is an ask from a kip user for custom VM size support on GCP because custom VM sizes are more resource and cost efficient for the applications they would like to deploy via kip on GCP. Lets track custom VM size for GCP in this issue. If and when there is a need for extending the feature to cloud providers beyond GCP, we will create a separate issue.

**Comment by jrroman** [comment]
Can this issue be closed since it PR #136 was merged?

**Comment by myechuri** [comment]
Thanks, @jrroman , for pointing out! Closing.

@ldx : thanks for the PR!
