### ISSUE TITLE
VK+KIP displays cells from a previous incarnation

### ISSUE THREAD

**Issue by myechuri** [elotl/kip#44]
1) Created 1 node vk+kip cluster - incarnation1 (KipControllerID `2qs4mvn2pza6teedd6hfz5hiky`)
2) Deployed nginx deployment with 1 replica - incarnation1
3) Deleted nginx deployment
4) Deleted virtual-kubelet deployment
5) Created virtual-kubelet deployment - incarnation2 (KipControllerID `72oxoqlbgrgjrleablteitvrxu`)
`kubectl get pods` shows zero pods.
`kubectl get cells` shows nginx and kube-proxy cells from incarnation1.

```
$ kubectl get pods
No resources found in default namespace.

$ kubectl get cells
NAME                                   POD NAME                            POD NAMESPACE   NODE              LAUNCH TYPE   INSTANCE TYPE   INSTANCE ID           IP
0dfd31cf-8d5a-494d-98e7-d8de2f4b4c9d   kube-proxy-rjspt                    kube-system     virtual-kubelet   On-Demand     t3.nano         i-0650833d57a649efd   172.31.74.58
61c44374-33aa-4636-8d09-23479025c3b4   kube-proxy-rjspt                    kube-system     virtual-kubelet   On-Demand     t3.nano         i-005c2fb81f90a1ede   172.31.77.142
66e5f0da-7f74-4a17-ac9b-fe6234ed8369   nginx-deployment-66f967f649-9b8zj   default         virtual-kubelet   On-Demand     t3.nano         i-0ec6eabbae4ca4c6b   172.31.72.109
```

<img width="1212" alt="Screen Shot 2020-03-12 at 12 52 58 PM" src="https://user-images.githubusercontent.com/12038016/76561436-863cf000-6460-11ea-8e8a-545f92c061f3.png">

**Comment by ldx** [comment]
Created #131 to deal with all resources left behind by a deleted Kip instance.
