### ISSUE TITLE
[Conformance] Virtual-Kubelet limits number of log lines

### ISSUE THREAD

**Issue by justnoise** [elotl/kip#49]
Kubelet's behavior is to display > 1000 log lines when getting logs with no options.  Virtual Kubelet, however, asks for 10 lines by default.  This ends up truncating log lines when running conformance tests and tests fail.

I believe the following tests are affected by this issue:

- [k8s.io] Pods should contain environment variables for services [NodeConformance] [Conformance]
[k8s.io] Variable Expansion should allow composing env vars into new env vars [NodeConformance] [Conformance]
[sig-api-machinery] Secrets should be consumable from pods in env vars [NodeConformance] [Conformance]
[sig-api-machinery] Secrets should be consumable via the environment [NodeConformance] [Conformance]
[sig-node] ConfigMap should be consumable via environment variable [NodeConformance] [Conformance]
[sig-node] ConfigMap should be consumable via the environment [NodeConformance] [Conformance]

We should (1) investigate exactly how the kubelet limits log lines it returns and (2) make an issue, followed by a PR to Virtual Kubelet to bring the behavior of logs into alignment with kubelet.

**Comment by justnoise** [comment]
Looks like there are already 2 PRs that fix this in different ways:
- https://github.com/virtual-kubelet/virtual-kubelet/pull/806
- https://github.com/virtual-kubelet/virtual-kubelet/pull/821

**Comment by ldx** [comment]
https://github.com/virtual-kubelet/virtual-kubelet/pull/806 has been merged, so this should be fixed.
