### ISSUE TITLE
Need to capture root disk size from image

### ISSUE THREAD

**Issue by justnoise** [elotl/kip#85]
Now that we've opened images up to allow the user to bring any image they want (assuming it has cloud-init installed), we need to start our instances with the correct minimum root volume size.  The root volume can't be smaller than the root disk image.

When querying for the boot image, we probably also want to store the retrieved image size and use that as the minimum specified size when booting the image.

**Comment by ldx** [comment]
We can do it in a similar way as in #84?

**Comment by justnoise** [comment]
I think that would work. It looks like both `describe-images` in AWS and `images.get` in GCE return the necessary info.  We can shove the disk size into the `cloud.Image` structure.
