### ISSUE TITLE
Set cluster-level GKE metadata entries for cells

### ISSUE THREAD

**Issue by ldx** [elotl/kip#91]
System pods in GKE expect the following metadata labels to be present for instances:
- cluster_name
- instance_id
- location
- node_name
- project_id

Even though we don't strictly need the system pods to be running via Kip, it's a bad UX that they start up automatically and will keep crashing due to the lack of these metadata on their instances. It should be easy for kip to check these labels for its own instance, and add them to each instance it starts.

**Comment by justnoise** [comment]
Our virtual-kubelet node has the following metadata keys present on the instance:
```
# curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/ -H "Metadata-Flavor: Google"
cluster-location
cluster-name
cluster-uid
configure-sh
created-by
disable-legacy-endpoints
enable-oslogin
gci-ensure-gke-docker
gci-update-strategy
google-compute-enable-pcid
instance-template
kube-env
kube-labels
kubelet-config
user-data
```

In PR https://github.com/elotl/kip/pull/108 I've added 3 of those keys to each instance we start. With that change, DaemonSets start correctly and report that they're running but any container having to do with stackdriver has errors in their logs:

```
Error while fetching metric descriptors for kube-proxy:
Get https://monitoring.googleapis.com/v3/projects/milpa-207719/metricDescriptors?alt=json&filter=metric.type+%3D+starts_with%28%22container.googleapis.com%2Finternal%2Faddons%2Fkube-proxy%22%29:
metadata: GCE metadata "instance/service-accounts/default/token" not defined
```

I we should consider what to do about handling service accounts in GCE/GKE.

**Comment by ldx** [comment]
I think sooner or later we'll have to add a service account to cells that allows logging and monitoring agents to send data to stackdriver. That might also fix the complaining daemonsets, though if they don't get into a crash loop, that's good enough.

**Comment by ldx** [comment]
Fixed via https://github.com/elotl/kip/pull/108
